### ISSUE TITLE
May I translate to Chinese? 

### ISSUE THREAD

**Issue by LukaHuang** [iLoveCodingOrg/javascript-cheatsheet#2]
Hi, azizali 

May I translate this cheatsheet to Chinese for sharing?  
I will make sure indicate the original post, title author name. 

Best Regards, 
Steven

**Comment by azizali** [comment]
sure please post a pull request here so everyone can benefit

Thank you so much


Aziz Ali
Founder of iLoveCoding Inc.

*E: aziz@iLoveCoding.org*
*P: 630.724.7322*
*W: iLoveCoding.org <https://ilovecoding.org/>*
Twitter <https://twitter.com/ilovecodingorg> Facebook
<https://www.facebook.com/ilovecodingorg> Linkedin
<https://www.linkedin.com/in/azizali/>

*P.S.* Upgrade your skills + Become a Ninja Software Developer, *with
proper guidance* along the way. Learn more at iLoveCoding.org
<http://ilovecoding.org/> or simply ask me about it.

*P.P.S.* Check out AzizAli <http://azizali.com/>.com <http://azizali.com/> (my
personal website)
